export const FIVE_DAY_REQUEST = 'FIVE_DAY_REQUEST';
export const FIVE_DAY_SUCCESS = 'FIVE_DAY_SUCCESS';
export const FIVE_DAY_ERROR = 'FIVE_DAY_ERROR';
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
